# https://proceedings.mlr.press/v162/sakr22a/sakr22a.pdf

from .convolution_weight_quantization import LinQuantWeight_mod_OCTAV as OCTAV_convolution_weight_quantization
from .linear_weight_quantization import LinQuantWeight_mod_OCTAV as OCTAV_linear_weight_quantization